config/routes.rb
Rails.application.routes.draw do
  resources :swords
  resources :victims
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sword.rb
class Sword < ApplicationRecord
  belongs_to :user
  belongs_to :victim
  validates :length, length: { minimum: 2 }
  validates :length, length: { maximum: 16 }
  validates :material, format: { with: /\A[a-zA-Z]+\z/, message: "Only letters allowed" }
  validates :length, presence: true
  validates :material, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :swords
  has_many :victims, through: :swords
  validates_associated :swords
  validates_associated :victims
  validates :name, presence: true
  validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "Only letters allowed" }
  validates :age, format: { with: /\A[0-9]+\z/, message: "Only numbers allowed" }
  validates :gender, inclusion: { in: %w(o O m M f F), }
end

app/models/victim.rb
class Victim < ApplicationRecord
  validates :name, presence: true
  validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "Only letters allowed" }
  validates :date_of_death, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/swords_controller.rb
class SwordsController < ApplicationController
  before_action :set_sword, only: [:show, :edit, :update, :destroy]

  # GET /swords
  # GET /swords.json
  def index
    @swords = Sword.all
    @users = User.all
    @victims = Victim.all
  end

  # GET /swords/1
  # GET /swords/1.json
  def show
  end

  # GET /swords/new
  def new
    @sword = Sword.new
    @users = User.all
    @victims = Victim.all
  end

  # GET /swords/1/edit
  def edit
    @users = User.all
    @victims = Victim.all
  end

  # POST /swords
  # POST /swords.json
  def create
    @sword = Sword.new(sword_params)

    respond_to do |format|
      if @sword.save
        format.html { redirect_to @sword, notice: 'Sword was successfully created.' }
        format.json { render :show, status: :created, location: @sword }
      else
        format.html { render :new }
        format.json { render json: @sword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swords/1
  # PATCH/PUT /swords/1.json
  def update
    respond_to do |format|
      if @sword.update(sword_params)
        format.html { redirect_to @sword, notice: 'Sword was successfully updated.' }
        format.json { render :show, status: :ok, location: @sword }
      else
        format.html { render :edit }
        format.json { render json: @sword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swords/1
  # DELETE /swords/1.json
  def destroy
    @sword.destroy
    respond_to do |format|
      format.html { redirect_to swords_url, notice: 'Sword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sword
      @sword = Sword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sword_params
      params.require(:sword).permit(:material, :length, :broken, :user_id, :victim_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :gender)
    end
end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  before_action :set_victim, only: [:show, :edit, :update, :destroy]

  # GET /victims
  # GET /victims.json
  def index
    @victims = Victim.all
  end

  # GET /victims/1
  # GET /victims/1.json
  def show
  end

  # GET /victims/new
  def new
    @victim = Victim.new
  end

  # GET /victims/1/edit
  def edit
  end

  # POST /victims
  # POST /victims.json
  def create
    @victim = Victim.new(victim_params)

    respond_to do |format|
      if @victim.save
        format.html { redirect_to @victim, notice: 'Victim was successfully created.' }
        format.json { render :show, status: :created, location: @victim }
      else
        format.html { render :new }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /victims/1
  # PATCH/PUT /victims/1.json
  def update
    respond_to do |format|
      if @victim.update(victim_params)
        format.html { redirect_to @victim, notice: 'Victim was successfully updated.' }
        format.json { render :show, status: :ok, location: @victim }
      else
        format.html { render :edit }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /victims/1
  # DELETE /victims/1.json
  def destroy
    @victim.destroy
    respond_to do |format|
      format.html { redirect_to victims_url, notice: 'Victim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_victim
      @victim = Victim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def victim_params
      params.require(:victim).permit(:name, :date_of_death, :dead)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/swords_helper.rb
module SwordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weapons</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/swords/_form.html.erb
<%= form_with(model: sword, local: true) do |form| %>
  <% if sword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sword.errors.count, "error") %> prohibited this sword from being saved:</h2>

      <ul>
      <% sword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :material %>
    <%= form.text_field :material %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length %>
  </div>

  <div class="field">
    <%= form.label :broken %>
    <%= form.check_box :broken %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= collection_select(:user, :user_id, @users, :id, :name)%>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :victim_id %>
      <%= collection_select(:victim, :victim_id, @victims, :id, :name)%>
    <%= form.text_field :victim_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/swords/edit.html.erb
<h1>Editing Sword</h1>

<%= render 'form', sword: @sword %>

<%= link_to 'Show', @sword %> |
<%= link_to 'Back', swords_path %>

app/views/swords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Swords</h1>

<table>
  <thead>
    <tr>
      <th>Material</th>
      <th>Length</th>
      <th>Broken</th>
      <th>User</th>
      <th>Victim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @swords.each do |sword| %>
      <tr>
        <td><%= sword.material %></td>
        <td><%= sword.length %></td>
        <td><%= sword.broken %></td>
        <td><%= sword.user.name %></td>
        <td><%= sword.victim.name %></td>
        <td><%= link_to 'Show', sword %></td>
        <td><%= link_to 'Edit', edit_sword_path(sword) %></td>
        <td><%= link_to 'Destroy', sword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sword', new_sword_path %>

app/views/swords/new.html.erb
<h1>New Sword</h1>

<%= render 'form', sword: @sword %>

<%= link_to 'Back', swords_path %>

app/views/swords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Material:</strong>
  <%= @sword.material %>
</p>

<p>
  <strong>Length:</strong>
  <%= @sword.length %>
</p>

<p>
  <strong>Broken:</strong>
  <%= @sword.broken %>
</p>

<p>
  <strong>User:</strong>
  <%= @sword.user.name %>
</p>

<p>
  <strong>Victim:</strong>
  <%= @sword.victim.name %>
</p>

<%= link_to 'Edit', edit_sword_path(@sword) %> |
<%= link_to 'Back', swords_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/victims/_form.html.erb
<%= form_with(model: victim, local: true) do |form| %>
  <% if victim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(victim.errors.count, "error") %> prohibited this victim from being saved:</h2>

      <ul>
      <% victim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date_of_death %>
    <%= form.text_field :date_of_death %>
  </div>

  <div class="field">
    <%= form.label :dead %>
    <%= form.check_box :dead %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/victims/edit.html.erb
<h1>Editing Victim</h1>

<%= render 'form', victim: @victim %>

<%= link_to 'Show', @victim %> |
<%= link_to 'Back', victims_path %>

app/views/victims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Victims</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of death</th>
      <th>Dead</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @victims.each do |victim| %>
      <tr>
        <td><%= victim.name %></td>
        <td><%= victim.date_of_death %></td>
        <td><%= victim.dead %></td>
        <td><%= link_to 'Show', victim %></td>
        <td><%= link_to 'Edit', edit_victim_path(victim) %></td>
        <td><%= link_to 'Destroy', victim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Victim', new_victim_path %>

app/views/victims/new.html.erb
<h1>New Victim</h1>

<%= render 'form', victim: @victim %>

<%= link_to 'Back', victims_path %>

app/views/victims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @victim.name %>
</p>

<p>
  <strong>Date of death:</strong>
  <%= @victim.date_of_death %>
</p>

<p>
  <strong>Dead:</strong>
  <%= @victim.dead %>
</p>

<%= link_to 'Edit', edit_victim_path(@victim) %> |
<%= link_to 'Back', victims_path %>